### PR TITLE
Wanted feature: allow enabling/disabling helmet HUD smooth follow

### PR DESCRIPTION
**Pull request by Maximetinu**
Hi folks 😄 !

I recently discovered this mod, and it's wonderful, bext VR experience I've ever had. It really looks like a native VR game. Congrats to @Raicuparta and the rest of contributors for it. It is filling the void that beating the DLC left inside me (for the second time, after beating the original game when it was released) and has given me the perfect excuse to run through the game once again, this time on VR.

I'm adding this feature because it's something that has annoyed me sometimes. Having the HUD slightly delayed behind my head movement works well on flat screen to increase immersion but it breaks it for me on VR, and I think it even contribute to nausea and motion sickness. It's well known that a common measure to reduce motion sicknes is having a fixed frame around the game view to look at. So this feature, imo, works in these 2 ways: it helps reducing motion sickness and, at least for me, increases immersion.

Here's a video that shows it working:

https://user-images.githubusercontent.com/16073309/137630209-5eac0f1d-111a-4152-b2b0-d9057989966d.mp4

I'd like to try the same for the removing the camera smoothness when flying the ship, but that is secondary and not as annoying (maybe it's even nicer, I'll know when I try it). Besides, I see that there are some issues reported and ongoing work to support the DLC, so you might see me around again contributing with something else :)

Happy hacking ! ✌️ 

P.S: I'm participating in hacktoberfest, if you could add the `hacktoberfest-accepted` label to the PR I'd appreciate it 👼

### CODE REVIEW

**Comment by Raicuparta** [comment]
That KS for the contribution! I've actually wanted to completely remove HUD smooth follow for a while, we might do that. But for now please wait until after we release NomaiVR 2.0.0, after that we'll look into this again.

**Comment by Raicuparta** [comment]
@Maximetinu sorry that it's been so long. NomaiVR 2.0.0 has been out for a while, but OWML had a bug where it wouldn't allow mod settings to scroll, so we couldn't consider adding this yet. If you're still interested, you'd need to update your PR to solve these conflicts (since I think you based your code on an older NomaiVR version).

**Comment by Maximetinu** [comment]
Sure, I’ll do it when I get a chance! (probably on a weekend, because I'm a
little short on time)

**Comment by Maximetinu** [comment]
Conflicts resolved 😁

**Comment by Raicuparta** [comment]
Works great! I had to fix an issue with a missing reference, and wanted to clean up that smooth follow file, so I made a separate PR based on yours (#490).

**Comment by Maximetinu** [comment]
Perfect! I forgot to mention but sure feel free to make any modifications! 🙂 Don't know how I missed that using without noticing 🤦‍♂️ I'm glad you fixed it, thanks

**Comment by Maximetinu** [comment]
The ship has a similar smoothing effect when you're flying it, do you have any clue in what part of the code could that be enabled/disabled too?

**Comment by Raicuparta** [comment]
The mod doesn't do any smoothing there, whatever you're seeing is a base game thing. For rotation there isn't any smoothing, but for movement the game has some kind of smoothed delay between the player body and ship body velocities.

**Comment by Maximetinu** [comment]
I see. Then I guess that if I want to disable that built-in smoothing behaviour from the base game, I will have to search for the class and method responsible for that in the original game assembly and create a new patch for it, inheriting from the `NomaiVRPatch` class, and empty the methods responsible for this smoothing with the `NomaiVRPatch.Empty<T>` method, right?

Is that more or less the right direction to start looking into this?

**Comment by Raicuparta** [comment]
Yep, something like that.

**Pull request closed without merging**
